[package]
name = "validate_sudoku_with_size_nxn"
version = "0.1.0"
authors = ["Eric Zhu <cupofc0t@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
